### ISSUE TITLE
Great  work！  Where is  the dataset?

### ISSUE THREAD

**Issue by c1a1o1** [CODEJIN/HiFiSinger#1]
Great  work！  Where is  the dataset??

**Comment by CODEJIN** [comment]
As I mentioned at Readme, I used a private dataset of limited size. It cannot be shared. The dataset which authors of HiFiSinger paper also collected their own dataset.

**Comment by c1a1o1** [comment]
Can you do a test on NUS-48E Sung and Spoken Lyrics Corpus dataset?
https://smcnus.comp.nus.edu.sg/nus-48e-sung-and-spoken-lyrics-corpus/

**Comment by CODEJIN** [comment]
Sorry. I can't. I don't think NUS-48E dataset is suitable for HiFiSinger. HiFiSinger is based on FastSpeech architecture and requires essentially the many songs like the size of TTS training datasets. Although NUS-48E is a good dataset, it is judged that there is too little data per singer to train the HiFiSinger.
