### ISSUE TITLE
Is `PWGAN_for_HiFiSinger` not public?

### ISSUE THREAD

**Issue by 3c1u** [CODEJIN/HiFiSinger#2]
Hi, I tried to use this program, but a link to the vocoder seems to be dead.

> * Vocoder_Path
>     * Setting the traced vocoder path.
>     * To generate this, please check [Here](https://github.com/CODEJIN/PWGAN_for_HiFiSinger)

**Comment by CODEJIN** [comment]
Sorry for late reply. Although I could not make README, I changed the repo to public. 

Thanks,

Heejo

**Comment by 3c1u** [comment]
Thank you for making it public! I tried [it](https://github.com/CODEJIN/PWGAN_for_HiFiSinger) and it seemed to work.
