### ISSUE TITLE
how can i

### ISSUE THREAD

**Issue by RevolGMPHL** [CODEJIN/HiFiSinger#4]

**Comment by RevolGMPHL** [comment]
how can i download the dataset.
and what is the content of PICKLE

**Comment by CODEJIN** [comment]
Unfortunately, as mentioned in the [README.MD](https://github.com/CODEJIN/HiFiSinger/blob/main/README.md#used-dataset), I validated this code on a limited size Korean dataset. Please note that this data is personal data and is difficult to disclose.

Currently, each Pickle file contains Mel, slience, pitch, text, duration of each grapheme information. Please refer [Pattern_Generator.py](https://github.com/CODEJIN/HiFiSinger/blob/3d7f323418d84512f2c75620c8e513949caffd1f/Pattern_Generator.py#L148-L158)
