### ISSUE TITLE
Open singing dataset CSD (Children's Song Dataset) may be used for your Work

### ISSUE THREAD

**Issue by YangWangGit** [CODEJIN/HiFiSinger#6]
I found your work is very interesting to my current research. Many thanks!

I noticed other people also questioned on the training corpus, which is necessary to reproduce your work completely. So the CSD (Children's Song Dataset) may be useful to make your code be much more influential for other researchers.   :-)

CSD (Children's Song Dataset) 
https://github.com/emotiontts/emotiontts_open_db/tree/master/Dataset/CSD

**Comment by CODEJIN** [comment]
Thank you for your notice! I checked the data set while implementing MLPSinger. I haven't been able to apply the dataset due to my recent main work, but I'll try it when I have some time.
