### ISSUE TITLE
A question about the duration

### ISSUE THREAD

**Issue by zfishbone01** [CODEJIN/HiFiSinger#7]
Hi, I am learning your code recently, but I got a question about the note's duration.
While I see a duration extract from midi file, is this duration the phoneme duration? or a word duration?
and is the groudtruth duration label predicted by an model ? not from some alignment tool like mfa?

Thanks!!

**Comment by CODEJIN** [comment]
Dear zfishbone01,

Hello,

1. The duration is the length of a syllable. And I premised the front and end of several frames of the syllable duration are the duration of an onset and a coda. However, in the case of Korean, both phoneme and grapheme are always in single C, single V, and single C form(CVC), so phoneme and grapheme match positionally, but other languages do not. If the language you are using has a structure in which multiple graphemes are combined to form a single phoneme, it is recommended to configure it based on phonemes.

2. The private data I used was hand-predicted data with DAW. However, HiFiSinger's original paper used MFA, so it is recommended to use MFA.
