### ISSUE TITLE
how can I convert xml file to midi

### ISSUE THREAD

**Issue by Jwei-Lee** [CODEJIN/HiFiSinger#8]

**Comment by CODEJIN** [comment]
Hi, Jwei,

Sorry but I don't quite understand your question. Do you mean that you have a music information file in xml? If that's the case, I can't really give you any specific advice unless I can see what the structure of the data is. And, even if the music file you have is xml, if the xml contains three pieces of information about a song; note, lyric, and duration, I think you can use the data.

Best regard.

**Comment by Jwei-Lee** [comment]
yes,this is a sample of xml file:
[sample.xml.txt](https://github.com/CODEJIN/HiFiSinger/files/7568205/sample.xml.txt)

**Comment by Jwei-Lee** [comment]
> Hi, Jwei,
> 
> Sorry but I don't quite understand your question. Do you mean that you have a music information file in xml? If that's the case, I can't really give you any specific advice unless I can see what the structure of the data is. And, even if the music file you have is xml, if the xml contains three pieces of information about a song; note, lyric, and duration, I think you can use the data.
> 
> Best regard.

yes, this is a sample of xml file:
[sample.xml.txt](https://github.com/CODEJIN/HiFiSinger/files/7568755/sample.xml.txt)

**Comment by Jwei-Lee** [comment]
I have use this "https://github.com/oov/mxl2mid" solved my problem.
